export const variables2 = [
    "Primer nombre",
     "Segundo nombre", "Primer apellido", "Segundo apellido", 
    "Tipo de Identificación", "Número de Identificación", "Fecha de nacimiento", 
    "Sexo", "Ocupación", "Régimen de afiliación AL SGSSS", "Código de la EPS o de la entidad territorial",
    "Código pertenencia étnica", "Grupo poblacional", "Municipio  de residencia", "Número telefónico del paciente (incluyendo a familiares y cuidadores)",
    "Fecha de afiliación a la EPS que registra", "Nombre de la neoplasia (cáncer o tumor) maligna reportada",
    "Fecha de diagnóstico del cáncer reportado actualmente", "Fecha de la nota de remisión del médico o institución general hacia la institución que hizo el diagnóstico",
    "Fecha de ingreso a la institución que realizó el diagnóstico luego de la remisión", 
    "Tipo de estudio con el que se realizó el diagnóstico de cáncer",
    "Motivo por el cual el usuario no tuvo diagnóstico por histopatología a la fecha de corte",
    "Fecha de recolección de muestra para estudio histopatológico",
    "Fecha primer o unico informe histopatológico válido",
    "Código válido de habilitación de la IPS donde se realiza la confirmación diagnóstica",
    "Fecha de primera consulta con médico tratante de la enfermedad maligna",
    "Histología del tumor en muestra de biopsia o quirúrgica",
    "Grado de diferenciación del tumor sólido maligno según la biopsia o informe de primera cirugía",
    "Si es tumor sólido, cuál fue la primera estadificación basada en TNM, FIGO, u otras compatibles con esta numeración según tumor:",
    "Fecha en que se realizó esta estadificación",
    "Para cáncer de mama, ¿se le realizó a este usuario la prueba HER2 (llamado también receptor 2 del factor de crecimiento epidérmico humano, también llamado erb-B2) antes del inicio del tratamiento?:",
    "Para cáncer de mama, fecha de realización de la unica primera  prueba HER2",
    "Para cáncer de mama, resultado de la ultima prueba HER2",
    "Para cáncer colorrectal, estadificación de Dukes",
    "Fecha en que se realizó la estadificación de Dukes",
    "Estadificación clínica en linfoma no Hodgkin Pediátrico (Murphy), linfoma No Hodgkin Adulto y linfoma Hodgkin adulto-pediátrico (Ann Arbor o Lugano), Mieloma Múltiple u otros cánceres hematológicos:",
    "Para cáncer de próstata, valor de clasificación de la escala Gleason en el momento del diagnóstico",
    "Clasificación de riesgo leucemias o linfomas (para toda la población), y sólidos pediátricos (ver documento de apoyo Clasificación de Riesgo por tipo de cáncer, disponible en la página web CAC)",
    "Fecha de clasificación de riesgo",
    "Objetivo (o intención) del tratamiento médico inicial (al diagnóstico)",
    "Objetivo de la intervención médica durante el periodo de reporte.",
    "Tiene antecedente o padece de otro cáncer primario (es decir, tiene o tuvo otro tumor maligno diferente al que está notificando):",
    "Fecha de diagnóstico del otro cáncer primario",
    "Tipo (CIE-10) de ese cáncer antecedente o concur",
    "¿Recibió el usuario quimioterapia u otra terapia sistémica (por ejemplo, hormonoterapia) dentro del periodo de corte actual? (Aclaración: en esta sección solo incluya ciclos iniciados en este corte. Por favor, no incluya el último ciclo informado como actual en el corte anterior, así se haya terminado en el periodo actual de reporte).",
    "¿Cuántas fases de quimioterapia recibió el usuario en este corte? (aplica para hematolinfáticos)",
    "El usuario recibió en este corte  la fase de quimioterapia denominada Prefase o Citorreducción inicial  (aplica para hematolinfáticos, puede haber recibido más de una fase)",
    "El usuario recibió en este corte  la fase de quimioterapia denominada Inducción (aplica para hematolinfáticos, puede haber recibido más de una fase)",
    "El usuario recibió en este corte  la fase de quimioterapia denominada Intensificación  (aplica para hematolinfáticos, puede haber recibido más de una fase)",
    "El usuario recibió en este corte  la fase de quimioterapia denominada Consolidación  (aplica para hematolinfáticos, puede haber recibido más de una fase)",
    "El usuario recibió en este corte  la fase de quimioterapia denominada Reinducción (aplica para hematolinfáticos, puede haber recibido más de una fase)",
    "El usuario recibió en este corte  la fase de quimioterapia denominada  Mantenimiento (aplica para hematolinfáticos, puede haber recibido más de una fase)",
    "El usuario recibió en este corte  la fase de quimioterapia denominada  Mantenimiento largo o final (aplica para hematolinfáticos, puede haber recibido más de una fase)",
    "El usuario recibió en este corte  Otra fase de quimioterapia denominada diferente a las anteriores  (aplica para hematolinfáticos, puede haber recibido más de una fase)",
    "Número de ciclos iniciados y administrados en el periodo de reporte, incluyendo el que aún recibe en la fecha de finalización del periodo (aplica para todos los cánceres):",
    "Ubicación temporal del primer o único esquema en el periodo en relación al manejo oncológico:",
    "Fecha de inicio del primer o único esquema de quimioterapia que recibió en este periodo. Reporte la fecha de inicio del tratamiento actual, así haya sido iniciada previo al reporte actual:",
    "Número de IPS que suministran el primer o único esquema de este periodo de reporte:",
    "Código de la IPS1 que suministra el primer o único esquema de este periodo de reporte:",
    "Código de la IPS2 que suministra el primer o único esquema de este periodo de reporte:",
    "Cuantos medicamentos antineoplásicos, el (los) especialista(s) tratante(s) del cáncer propusieron como manejo en el primer o único esquema de este periodo de reporte:",
    "Medicamento antineoplasico administrado al usuario - Primer o unico esquema del periodo de reporte",
    "Medicamento antineoplasico administrado al usuario - Primer o unico esquema del periodo de reporte",
    "Medicamento antineoplasico administrado al usuario - Primer o unico esquema del periodo de reporte",
    "Medicamento antineoplasico administrado al usuario - Primer o unico esquema del periodo de reporte",
    "Medicamento antineoplasico administrado al usuario - Primer o unico esquema del periodo de reporte",
    "Medicamento antineoplasico administrado al usuario - Primer o unico esquema del periodo de reporte",
    "Medicamento antineoplasico administrado al usuario - Primer o unico esquema del periodo de reporte",
    "Medicamento antineoplasico administrado al usuario - Primer o unico esquema del periodo de reporte",
    "Medicamento antineoplasico administrado al usuario - Primer o unico esquema del periodo de reporte",
    "Medicamento antineoplasico administrado al usuario - Primer o unico esquema del periodo de reporte",
    "Medicamento antineoplasico administrado al usuario - Primer o unico esquema del periodo de reporte",
    "Medicamento antineoplasico administrado al usuario - Primer o unico esquema del periodo de reporte",
    "¿Recibió quimioterapia intratecal en el primer ciclo de este corte?",
    "Fecha de finalización del primer ciclo de este periodo de reporte.",
    "Características actuales del primer ciclo de este corte",
    "Motivo de la finalización (prematura) de este primer ciclo",
    "Ubicación temporal del último ciclo de este corte en relación al manejo oncológico",
    "Fecha de inicio del último ciclo de quimioterapia de este periodo de reporte.",
    "Número de IPS que suministran el último ciclo de este corte",
    "Código de la IPS1 que suministra el último ciclo en este reporte",
    "Código de la IPS2 que suministra el último ciclo en este reporte",
    "Cuantos medicamentos antineoplásicos, el (los) especialista(s) tratante(s) del cáncer propusieron como manejo en este último ciclo de este corte",
    "Medicamento antineoplasico administrado al usuario ultimo esquema del periodo de reporte",
    "Medicamento antineoplasico administrado al usuario ultimo esquema del periodo de reporte",
    "Medicamento antineoplasico administrado al usuario ultimo esquema del periodo de reporte",
    "Medicamento antineoplasico administrado al usuario ultimo esquema del periodo de reporte",
    "Medicamento antineoplasico administrado al usuario ultimo esquema del periodo de reporte",
    "Medicamento antineoplasico administrado al usuario ultimo esquema del periodo de reporte",
    "Medicamento antineoplasico administrado al usuario ultimo esquema del periodo de reporte",
    "Medicamento antineoplasico administrado al usuario ultimo esquema del periodo de reporte",
    "Medicamento antineoplasico administrado al usuario ultimo esquema del periodo de reporte",
    "Medicamento antineoplasico administrado al usuario ultimo esquema del periodo de reporte",
    "Medicamento antineoplasico administrado al usuario ultimo esquema del periodo de reporte",
    "Medicamento antineoplasico administrado al usuario ultimo esquema del periodo de reporte",
    "¿Recibió quimioterapia intratecal en el último ciclo de este corte?",
    "Fecha de finalización del último ciclo de este periodo de reporte. Si es hormonoterapia reporte la fecha de finalización del tratamiento actual",
    "Características actuales del último  ciclo de este corte",
    "Motivo de la finalización (prematura) de este último ciclo",
    "¿Fue sometido el usuario a una o más cirugías curativas o paliativas como parte del manejo del cáncer durante este periodo de reporte?:",
    "Número de cirugías a las que fue sometido el usuario durante el periodo de reporte actual",
    "Fecha de realización de la primera cirugía en este reporte",
    "Código de la IPS  que realizó la primera cirugía de este corte",
    "Código de primera cirugía",
    "Ubicación temporal de esta primera cirugía en relación al manejo oncológico",
    "Fecha de realización de la última cirugía o cirugía de reintervención en este periodo de reporte",
    "Motivo de haber realizado la última intervención quirúrgica de este corte",
    "Código de la IPS que realiza la última cirugía en este periodo de reporte",
    "Código de última cirugía en este periodo de reporte",
    "Ubicación temporal de esta última cirugía en relación al manejo oncológico, en este corte",
    "Estado vital al finalizar la única o última cirugía de este corte",
    "¿Recibió el usuario algún tipo de radioterapia en el corte actual?",
    "Número de sesiones de radioterapia suministradas en el corte actual",
    "Fecha de inicio de primer o único esquema de radioterapia suministrado en el corte actual",
    "Ubicación temporal del primer o único esquema de radioterapia en este corte",
    "Tipo de radioterapia aplicada en este primer o único esquema",
    "Número de IPS que suministran este primer o único esquema de radioterapia",
    "Código de la IPS1 que suministra la radioterapia de este primer o único esquema:",
    "Código de la IPS2 que suministra la radioterapia de este primer o único esquema:",
    "Fecha de finalización de primer o único esquema de radioterapia",
    "Características actuales de este primer o único esquema de radioterapia",
    "Motivo de la finalización de este primer o único esquema de radioterapia (Aplica si registró la opción 2 de la pregunta anterior) Selecciona un sólo número (lo que primero ocurrió).",
    "Fecha de inicio del último esquema de radioterapia suministrado en el corte actual",
    "Ubicación temporal del último esquema de radioterapia suministrado en el corte actual",
    "Tipo de radioterapia aplicada en el último esquema de radioterapia suministrado en el corte actual",
    "Número de IPS que suministran este  último esquema de radioterapia suministrado en el corte actual",
    "Código de la IPS1 que suministra la radioterapia",
    "Código de la IPS2 que suministra la radioterapia",
    "Fecha de finalización del último esquema de radioterapia suministrado en el corte actual",
    "Características actuales de este último esquema de radioterapia suministrado en el corte actual",
    "Motivo de la finalización de este último esquema de radioterapia suministrado en el corte actual (Aplica si registró la opción 2 de la pregunta anterior) Selecciona un sólo número (lo que primero ocurrió).",
    "¿Recibió el usuario trasplante de células progenitoras hematopoyéticas dentro del periodo de corte actual?",
    "Tipo de trasplante recibido",
    "Ubicación temporal de este trasplante en relación al manejo oncológico",
    "Fecha de trasplante", "Código de la IPS que realizó este trasplante", 
    "El usuario, ¿recibió cirugía reconstructiva?",
     "Fecha de la cirugía reconstructiva",
     "Código de la IPS que realizó cirugía reconstructiva",
     "¿El usuario fue valorado en consulta o procedimiento de cuidado paliativo durante este corte? (pueden haber sido múltiples)",
     "El usuario recibió consulta o procedimiento de cuidado paliativo en este corte, por médico especialista en cuidado paliativo",
     "El usuario recibió consulta o procedimiento de cuidado paliativo en este corte, por profesional de la salud (no médico, incluye psicólogo) especialista en cuidado paliativo",
     "El usuario recibió consulta o procedimiento de cuidado paliativo en este corte, por médico especialista, otra especialidad",
     "El usuario recibió consulta o procedimiento de cuidado paliativo en este corte, por médico general",
     "El usuario recibió consulta o procedimiento de cuidado paliativo en este corte, por trabajo social",
     "El usuario recibió consulta o procedimiento de cuidado paliativo en este corte, por otro profesional de salud (no médico, incluye psicólogo) no especializado",
     "Fecha de primera consulta o procedimiento de cuidado paliativo en este corte",
     "Código de la IPS donde recibió la primera valoración de cuidado Paliativo",
     "¿Ha sido valorado el usuario por el servicio de psiquiatría durante este corte?",
     "Fecha de primera consulta con el servicio de psiquiatría (para todos los usuarios) en este corte",
     "Código de la IPS  donde recibió la primera valoración de psiquiatría en este corte",
     "¿Fue valorado el usuario por profesional en nutrición durante este corte?",
     "Fecha de consulta inicial con nutrición en este corte",
     "Código de la IPS donde recibió la valoración por nutrición, en este corte",
     "¿El usuario recibió soporte nutricional?",
     "¿El usuario ha recibido terapias complementarias para su rehabilitación?",
     "Tipo de tratamiento que está recibiendo el usuario a la fecha de corte ",
     "Resultado final del manejo oncológico en este corte",
     "Estado vital al finalizar este corte",
     "Novedad Administrativa respecto al reporte anterior",
     "Novedad clínica  a la fecha de corte",
     "Fecha de desafiliación de la EPS",
     "Fecha de muerte",
     "Causa de muerte",
     "Código único de identificación"]